# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [19]:
import numpy as np
a = np.arange(45).reshape(3, 5, 3)
print(a)
print('list(a): ', list(a))
print('tolist(): ', a.tolist())

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]]
list(a):  [array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]]), array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]]), array([[30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])]
tolist():  [[[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11], [12, 13, 14]], [[15, 16, 17], [18, 19, 20], [21, 22, 23], [24, 25, 26], [27, 28, 29]], [[30, 31, 32], [33, 34, 35], [36, 37, 38], [39, 40, 41], [42, 43, 44]]]


### ANS1：
list()只能最外層，a.tolist可以將屬性完全轉成list，即使a陣列的維度再高也可以

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [53]:
# 記得先 Import 正確的套件
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2))
print(f'a:\n{a}\nb:\n{b}\nc:\n{c}')
import pandas as pd
ans2 = pd.DataFrame({'ndim':[a.ndim,b.ndim,c.ndim],
                   'shape':[a.shape,b.shape,c.shape],
                   'size':[a.size,b.size,c.size],
                   'dtype':[a.dtype,b.dtype,c.dtype],
                   'itemsize':[a.itemsize,b.itemsize,c.itemsize],
                   'length':[len(a),len(b),len(c)],
                   'type':[type(a),type(b),type(c)]},index=list('abc'))
ans2

a:
[9 0 4 0 7 0]
b:
[[5 4 0 0]
 [7 3 7 8]
 [2 5 0 8]]
c:
[[[8 6]
  [3 1]
  [4 5]]

 [[2 3]
  [2 2]
  [5 0]]]


ndim      shape  size  dtype  itemsize  length                     type
a     1       (6,)     6  int32         4       6  <class 'numpy.ndarray'>
b     2     (3, 4)    12  int32         4       3  <class 'numpy.ndarray'>
c     3  (2, 3, 2)    12  int32         4       2  <class 'numpy.ndarray'>

## ANS2：
陣列由數行開始(如xy座標圖的x軸)<br>
ndim直接讀維度<br>
shape讀具體行列與更高維的資料數<br>
size為總資料數（各維資料數的積）<br>
dtype為資料型態，包含位元<br>
length只看最高維度的個數<br>
itemsize為陣列中每個元素佔用的空間<br>
type查看類型

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [90]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))

[9, 4, 3, 2, 6, 3]
[9, 4, 3, 2, 6, 3]


In [91]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))

[[9, 4, 0, 7], [0, 5, 9, 2], [4, 9, 2, 5]]
[array([9, 4, 0, 7]), array([0, 5, 9, 2]), array([4, 9, 2, 5])]


In [92]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))

[[[3, 0], [0, 2], [4, 7]], [[8, 3], [3, 5], [3, 4]]]
[array([[3, 0],
       [0, 2],
       [4, 7]]), array([[8, 3],
       [3, 5],
       [3, 4]])]


In [121]:
# 陣列屬性走if，內容走else
def tolist(iterable):
    L=[]
    if type(iterable) == np.ndarray:
        return [tolist(i) for i in iterable]    
    else:
        return iterable

print(tolist(a))
print(tolist(b))
print(tolist(c))

[9, 4, 3, 2, 6, 3]
[[9, 4, 0, 7], [0, 5, 9, 2], [4, 9, 2, 5]]
[[[3, 0], [0, 2], [4, 7]], [[8, 3], [3, 5], [3, 4]]]
