# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [25]:
%timeit -n 100000 np.full((2, 3),0)
%timeit -n 100000 np.zeros((2, 3))
%timeit -n 100000 np.empty((2, 3))
%timeit -n 100000 a = np.empty((2, 3));a[:] = 0

2.12 µs ± 206 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
320 ns ± 8.96 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
364 ns ± 13.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
1 µs ± 47.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### ANS：
感覺兩者可以和np.full((2,3),0)比較<br>
建立時zeros與empty差不多，但是empty內資料是非零，如果要將陣列當矩陣用可能會遇到未歸零的人為誤差<br>
而要將empty再轉為零會比直接zeros耗時

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [55]:
# 記得先 Import 正確的套件
import numpy as np
import math
a = np.random.rand(2, 3)
a = a*100
a

array([[ 6.7397128 , 15.82424449, 32.16222607],
       [71.02363542, 40.18303603, 88.8532484 ]])

In [58]:
# 參考解答
a.round(0)
#或是np.round(a)

array([[ 7., 16., 32.],
       [71., 40., 89.]])

### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [71]:
#目標：變異範圍從0~1變成20~40

#證明：
#1 . (0~1) + 1 = (1~2)
#2 . (1~2) * 20 = (20~40)
#m, n 帶入
#3 . ((n/m)-1 ~ n/m) * m = (n-m) ~ n，也就是 m - n 之間
#回到 1，也就是 1 = (n/m)-1
m = 20
n = 40
(np.random.rand(2,3)+((n/m)-1))*m

array([[37.92151697, 30.40523937, 22.87202685],
       [38.20583766, 20.27218155, 27.83042981]])