作業目標<br>
計算有缺失值的資料，統計量實作<br>
作業重點<br>
當遇到缺失值有函式可以處理，不須額外寫程式刪除<br>
計算統計量時不能出現缺失值

題目:<br>
english_score = np.array([55,89,76,65,48,70])<br>
math_score = np.array([60,85,60,68,np.nan,60])<br>
chinese_score = np.array([65,90,82,72,66,77])<br>
上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，今天第五位同學因某原因沒來考試，導致數學成績缺值，運用上列數據回答下列問題。<br>
1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
3. 用補考後資料找出與國文成績相關係數最高的學科?

In [1]:
import numpy as np

In [2]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

In [57]:
#1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
english_mean=np.mean(english_score)
math_mean=np.nanmean(math_score)
chinese_mean=np.mean(chinese_score)
english_max=np.max(english_score)
math_max=np.nanmax(math_score)
chinese_max=np.max(chinese_score)
english_min=np.min(english_score)
math_min=np.nanmin(math_score)
chinese_min=np.min(chinese_score)
english_std=np.std(english_score)
math_std=np.nanstd(math_score)
chinese_std=np.std(chinese_score)
print('依序為 {:<5}{:<5}{:<5}'.format('英文','數學','國文'))
print('平均　 {:<7.1f}{:<7.1f}{:<7.1f}'.format(english_mean,math_mean,chinese_mean))
print('最大值 {:<7.0f}{:<7.0f}{:<7.0f}'.format(english_max,math_max,chinese_max))
print('最小值 {:<7.0f}{:<7.0f}{:<7.0f}'.format(english_min,math_min,chinese_min))
print('標準差 {:<7.2f}{:<7.2f}{:<7.2f}'.format(english_std,math_std,chinese_std))

依序為 英文   數學   國文   
平均　 67.2   64.7   75.3   
最大值 89     85     90     
最小值 48     55     65     
標準差 13.43  9.86   8.83   


In [58]:
#2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
math_score[4]=55
math_mean2=np.mean(math_score)
math_max2=np.max(math_score)
math_min2=np.min(math_score)
math_std2=np.std(math_score)
print('數學成績　平均：%.1f，最大值：%d，最小值：%d，標準差：%.2f' % (math_mean2,math_max2,math_min2,math_std2))

數學成績　平均：64.7，最大值：85，最小值：55，標準差：9.86


In [59]:
#3. 用補考後資料找出與國文成績相關係數最高的學科?
np.corrcoef([chinese_score,english_score,math_score])
#Ans:英文與國文有高度相關(約0.98)

國文 英文 數學


array([[1.        , 0.97792828, 0.74056803],
       [0.97792828, 1.        , 0.7855563 ],
       [0.74056803, 0.7855563 , 1.        ]])

In [79]:
import scipy.stats.stats as sp
L=[chinese_score,english_score,math_score]
corr=[]
corrp=[]
for i in L:
    for j in L:
        corr.append(list(sp.pearsonr(i,j))[0])
        corrp.append(list(sp.pearsonr(i,j))[1])
print('相關係數：\n國英數\n',np.reshape(corr,(3,3)))
print('P值：\n國英數\n',np.reshape(corrp,(3,3)))

相關係數：
國英數
 [[1.         0.97792828 0.74056803]
 [0.97792828 1.         0.7855563 ]
 [0.74056803 0.7855563  1.        ]]
P值：
國英數
 [[0.         0.00072536 0.0922269 ]
 [0.00072536 0.         0.06404843]
 [0.0922269  0.06404843 0.        ]]
